name: Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '44 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run hourly
        env:
          EVE_CLIENT_ID: ${{ vars.EVE_CLIENT_ID }}
          EVE_SECRET_KEY: ${{ secrets.EVE_SECRET_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
